twist_mux:
  ros__parameters:

    use_stamped: true

    topics:
      joystick:
        topic   : /cmd_vel_joy
        timeout : 0.5
        priority: 100
      nav2:
          topic   : /cmd_vel_nav
          timeout : 0.5
          priority: 50
