velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false

    max_velocity: [0.3, 0.0, 1.0]
    min_velocity: [-0.2, 0.0, -1.0]

    max_accel: [0.5, 0.0, 1.5]
    max_decel: [-0.5, 0.0, -1.5]

    odom_topic: /odom
    velocity_timeout: 0.5